CREATE TABLE Yazarlar 
  ( 
    yazar_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY       , 
    ad     VARCHAR2( 50 ) NOT NULL, 
    soyad VARCHAR2( 50 ) NOT NULL, 
    kategori VARCHAR2( 50 ) NOT NULL, 
    yayin_tarihi DATE 
  );

  CREATE TABLE Kitaplar 
  ( 
    kitap_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    yazar_id NUMBER NOT NULL, 
    kitap_ad     VARCHAR2( 100 ) NOT NULL, 
    sayfa_sayisi NUMBER NOT NULL, 
    isbn NUMBER NOT NULL, 
    Yayin_tarihi DATE, 
    CONSTRAINT fk_kitap_yazarlar  
      FOREIGN KEY( yazar_id ) 
      REFERENCES Yazarlar( yazar_id )  
      ON DELETE SET NULL 
  );

  CREATE TABLE Kutuphaneler 
  ( 
    kutuphane_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    kitap_id     NUMBER NOT NULL, 
    kutuphane_ad VARCHAR2( 100 ) NOT NULL, 
    telefon CHAR(11) NOT NULL, 
    posta_kodu VARCHAR2( 20 ), 
    şehir        VARCHAR2( 50 ),          
    CONSTRAINT fk_kütüphane_kitaplar  
      FOREIGN KEY( kitap_id ) 
      REFERENCES Kitaplar( kitap_id )  
      ON DELETE SET NULL 
  );

 INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal',DATE '1923-10-06');

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal','1923-10-06');

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal',to_date('1923-10-06'));

CREATE TABLE Yazarlar 
  ( 
    yazar_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY       , 
    ad     VARCHAR2( 50 ) NOT NULL, 
    soyad VARCHAR2( 50 ) NOT NULL, 
    dogum_tarihi DATE, 
    yas NUMBER AS (year from sysdate  - year from dogum_tarihi) 
  );

  CREATE TABLE Kitaplar 
  ( 
    kitap_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    yazar_id NUMBER NOT NULL, 
    kitap_ad     VARCHAR2( 100 ) NOT NULL, 
    sayfa_sayisi NUMBER NOT NULL, 
    isbn NUMBER NOT NULL, 
    Yayin_tarihi DATE, 
    CONSTRAINT fk_kitap_yazarlar  
      FOREIGN KEY( yazar_id ) 
      REFERENCES Yazarlar( yazar_id )  
      ON DELETE SET NULL 
  );

  CREATE TABLE Kutuphaneler 
  ( 
    kutuphane_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    kitap_id     NUMBER NOT NULL, 
    kutuphane_ad VARCHAR2( 100 ) NOT NULL, 
    telefon CHAR(11) NOT NULL, 
    posta_kodu VARCHAR2( 20 ), 
    şehir        VARCHAR2( 50 ),          
    CONSTRAINT fk_kütüphane_kitaplar  
      FOREIGN KEY( kitap_id ) 
      REFERENCES Kitaplar( kitap_id )  
      ON DELETE SET NULL 
  );

DROP TABLE Yazarlar;

DROP TABLE Kitaplar;

DROP TABLE Kutuphaneler;

drop table "KITAPLAR" cascade constraints;

DROP TABLE Kutuphaneler;

DROP TABLE Yazarlar;

DROP TABLE Kutuphaneler;

DROP TABLE Kitaplar;

CREATE TABLE Yazarlar 
  ( 
    yazar_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY       , 
    ad     VARCHAR2( 50 ) NOT NULL, 
    soyad VARCHAR2( 50 ) NOT NULL, 
    dogum_tarihi DATE, 
    yas NUMBER AS (year from sysdate  - year from dogum_tarihi) 
  );

  CREATE TABLE Kitaplar 
  ( 
    kitap_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    yazar_id NUMBER NOT NULL, 
    kitap_ad     VARCHAR2( 100 ) NOT NULL, 
    sayfa_sayisi NUMBER NOT NULL, 
    isbn NUMBER NOT NULL, 
    Yayin_tarihi DATE, 
    CONSTRAINT fk_kitap_yazarlar  
      FOREIGN KEY( yazar_id ) 
      REFERENCES Yazarlar( yazar_id )  
      ON DELETE SET NULL 
  );

  CREATE TABLE Kutuphaneler 
  ( 
    kutuphane_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    kitap_id     NUMBER NOT NULL, 
    kutuphane_ad VARCHAR2( 100 ) NOT NULL, 
    telefon CHAR(11) NOT NULL, 
    posta_kodu VARCHAR2( 20 ), 
    şehir        VARCHAR2( 50 ),          
    CONSTRAINT fk_kütüphane_kitaplar  
      FOREIGN KEY( kitap_id ) 
      REFERENCES Kitaplar( kitap_id )  
      ON DELETE SET NULL 
  );

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal',to_date('1923-10-06'));

CREATE TABLE Yazarlar 
  ( 
    yazar_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY       , 
    ad     VARCHAR2( 50 ) NOT NULL, 
    soyad VARCHAR2( 50 ) NOT NULL, 
    dogum_tarihi DATE, 
    yas NUMBER AS (year from sysdate  - year from dogum_tarihi) 
  );

  CREATE TABLE Kitaplar 
  ( 
    kitap_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    yazar_id NUMBER NOT NULL, 
    kitap_ad     VARCHAR2( 100 ) NOT NULL, 
    sayfa_sayisi NUMBER NOT NULL, 
    isbn NUMBER NOT NULL, 
    Yayin_tarihi DATE, 
    CONSTRAINT fk_kitap_yazarlar  
      FOREIGN KEY( yazar_id ) 
      REFERENCES Yazarlar( yazar_id )  
      ON DELETE SET NULL 
  );

  CREATE TABLE Kutuphaneler 
  ( 
    kutuphane_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    kitap_id     NUMBER NOT NULL, 
    kutuphane_ad VARCHAR2( 100 ) NOT NULL, 
    telefon CHAR(11) NOT NULL, 
    posta_kodu VARCHAR2( 20 ), 
    şehir        VARCHAR2( 50 ),          
    CONSTRAINT fk_kütüphane_kitaplar  
      FOREIGN KEY( kitap_id ) 
      REFERENCES Kitaplar( kitap_id )  
      ON DELETE SET NULL 
  );

CREATE TABLE Yazarlar 
  ( 
    yazar_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY       , 
    ad     VARCHAR2( 50 ) NOT NULL, 
    soyad VARCHAR2( 50 ) NOT NULL, 
    dogum_tarihi DATE, 
    sehir VARCHAR2( 50 ) NOT NULL 
  );

  CREATE TABLE Kitaplar 
  ( 
    kitap_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    yazar_id NUMBER NOT NULL, 
    kitap_ad     VARCHAR2( 100 ) NOT NULL, 
    sayfa_sayisi NUMBER NOT NULL, 
    isbn NUMBER NOT NULL, 
    Yayin_tarihi DATE, 
    CONSTRAINT fk_kitap_yazarlar  
      FOREIGN KEY( yazar_id ) 
      REFERENCES Yazarlar( yazar_id )  
      ON DELETE SET NULL 
  );

  CREATE TABLE Kutuphaneler 
  ( 
    kutuphane_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  
                PRIMARY KEY, 
    kitap_id     NUMBER NOT NULL, 
    kutuphane_ad VARCHAR2( 100 ) NOT NULL, 
    telefon CHAR(11) NOT NULL, 
    posta_kodu VARCHAR2( 20 ), 
    şehir        VARCHAR2( 50 ),          
    CONSTRAINT fk_kütüphane_kitaplar  
      FOREIGN KEY( kitap_id ) 
      REFERENCES Kitaplar( kitap_id )  
      ON DELETE SET NULL 
  );

 INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal',to_date('1923-10-06'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal','1923-10-06','İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES('Yaşar', 'Kemal',to_date('1923-10-06','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi) 
VALUES(1,'Yaşar', 'Kemal',to_date('1923-10-06','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum-tarihi,sehir) 
VALUES('Yaşar', 'Kemal',to_date('1923-10-06','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum_tarihi,sehir) 
VALUES('Yaşar', 'Kemal',to_date('1923-10-06','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum_tarihi,sehir) 
VALUES('Oğuz', 'Atay',to_date('1934-10-12','yyyy-mm-dd'),'Ankara');

  INSERT INTO Yazarlar(ad, soyad, dogum_tarihi,sehir) 
VALUES('Ahmet Hamdi', 'Tanpınar',to_date('1901-06-23','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum_tarihi,sehir) 
VALUES('Orhan', 'Pamuk',to_date('1952-06-07','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Yazarlar(ad, soyad, dogum_tarihi,sehir) 
VALUES('Yaşar', 'Kemal',to_date('1914-09-15','yyyy-mm-dd'),'İstanbul');

  INSERT INTO Kitaplar(kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES('İnce Memed', 436,4514949464,to_date('2020-02-28','yyyy-mm-dd'));

  INSERT INTO Kitaplar(kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES(1,'İnce Memed', 436,4514949464,to_date('2020-02-28','yyyy-mm-dd'));

  INSERT INTO Kitaplar(yazar_id,kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES(1,'İnce Memed', 436,4514949464,to_date('2020-02-28','yyyy-mm-dd'));

 INSERT INTO Kitaplar(yazar_id,kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES(2,'Tutunamayanlar ', 436,94848151,to_date('2018-07-14','yyyy-mm-dd'));

 INSERT INTO Kitaplar(yazar_id,kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES(3,'Saatleri Ayarlama Enstitüsü', 455,87849494,to_date('1998-06-16','yyyy-mm-dd'));

 INSERT INTO Kitaplar(yazar_id,kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES(4,'Kara Kitap', 500,641164445,to_date('2003-11-18','yyyy-mm-dd'));

 INSERT INTO Kitaplar(yazar_id,kitap_ad, sayfa_sayisi, isbn,Yayin_tarihi) 
VALUES(5,'Bereketli Topraklar Üzerinde', 300,21164645,to_date('2016-01-05','yyyy-mm-dd'));

  INSERT INTO Kutuphaneler(kitap_id,kutuphane_ad, telefon, posta_kodu,şehir) 
VALUES(1,'Ankara merkez kütüphane', 02062322525,06200,'Ankara');

CREATE SYNONYM SYN_Kitaplar 
FOR Kitaplar;

CREATE VIEW View_Yazarlar AS 
SELECT 
    ad, 
    soyad 
FROM 
    Yazarlar;

